### ISSUE TITLE
Mace Damage Calculator produces wrong values when crit is unchecked

### ISSUE THREAD

**Issue by Robotgiggle** [mc-wiki/mcw-calc#20]
Something appears to be wrong with the crit checkbox on the mace damage calculator. When the box is checked, the calculator works fine. However, when the box is _unchecked_, the values produced seem to be lower than they should be, by a flat offset of exactly 5.6. 

This can be seen with any fall height (ie 10 blocks should deal `7 + 10*3 = 37` damage, but the calculator produces 31.4) but it's most obvious when a fall height between 1.5 and 1.85 is used – at which point the calculator claims that a non-critical attack will deal less damage than the base attack damage of the mace.

**Comment by Dianliang233** [comment]
This is because the tool assumes that you are not dealing crits because you didn't reach the attack cooldown, which has a *0.2 modifier on your base damage. This is probably fixed in 7ede2469e8e9182f5456dbc7c102a2391ff59012
