### ISSUE TITLE
Some comments containing file links adds unnecessary entry "Category:Pages with broken file links"

### ISSUE THREAD

**Issue by bilintsui** [mc-wiki/mcw-calc#26]
The file links in comments are intended to register a file usage, on English Minecraft Wiki, it works well.

But in other languages' Minecraft Wiki, it might add unnecessary entry to "Category:Pages with broken file links", when this file is not exist (see [zh:Category:含有受损文件链接的页面](https://zh.minecraft.wiki/w/Category:含有受损文件链接的页面)). Since language wikis are all using the image file uploaded in the English one, these comments should be different in language wikis.

**Comment by Dianliang233** [comment]
It is basically impossible to control if the comments are shown for language wikis. I've removed them altogether
