### ISSUE TITLE
Block Distribution Tool Floats Incorrectly

### ISSUE THREAD

**Issue by Leo-768** [mc-wiki/mcw-calc#28]
Expected Results:
![image](https://github.com/mc-wiki/mcw-calc/assets/66005818/d8786172-8107-4225-8d11-1af3781abec9)
Actual Results:
![image](https://github.com/mc-wiki/mcw-calc/assets/66005818/8034a507-c65e-468b-91dd-5648cc0d4b68)

**Comment by Leo-768** [comment]
I think it's happening again.

**Comment by Dianliang233** [comment]
@Leo-768 could you provide an example? also i think there's a good chance that this is unfixable

**Comment by Leo-768** [comment]
![image](https://github.com/mc-wiki/mcw-calc/assets/66005818/d4b8cadc-dcb5-4489-9c3f-bb5992d53771)
For the page with a long infobox, it can cause a large blank space. In addition, if you switch tabs or click a collapse toggle in the infobox, the length of the page will change accordingly
